import type { Metadata } from 'next';
import { inter } from '@/app/ui/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s |Tableau de bord ACME',
    default: 'Tableau de bord ACME',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} ${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
